### ISSUE TITLE
When will it be ready for testing?

### ISSUE THREAD

**Issue by dimeldo** [qywu/ARDM#1]
Hello! Just read your paper. Very interesting. When will it be ready for testing? I would like to try your model on open-domain chit-chat data. Do you think it would work well on it?

Keep up the good work.

**Comment by qywu** [comment]
Thank you for your interest. The model should work well on chit-chat as it is designed to be general.
The code is still preliminary, but I would try to make a colab demo so people can try themselves and finetune on their dataset. I will try to get it done before next week.

**Comment by dimeldo** [comment]
That will be awesome! Thank you so much.

**Comment by qywu** [comment]
I have written two colab files. Hope it will help you.

Training: https://colab.research.google.com/drive/1RmC3-kyNdSEKrzUVcPB3lRmn_lnCi66T

Inference: https://colab.research.google.com/drive/1ib7YCeNhkIDAzuOKotSlw1CfIBP_zE4r

**Comment by dimeldo** [comment]
Thank you so much! I highly appreciate that. Can't wait to test your model.
