### ISSUE TITLE
how to get processed multiwoz dataset

### ISSUE THREAD

**Issue by luweishuang** [qywu/ARDM#4]
in your "multiwoz/MultiWOZ Multi-Turn Train.ipynb" have read some processed multiwoz data, as 
`with open("../yichi_data/clean_train_data.json") as f:
    train_data = json.load(f)
    
with open("../yichi_data/val_data.json") as f:
    val_data = json.load(f)
    
with open("../yichi_data/test_data.json") as f:
    test_data = json.load(f)`
what do you do to get this data and you used multiwoz2.1 or multiwoz2.0 ? thanks

**Comment by qywu** [comment]
We used MultiWOZ2.0. But we used slightly different delexicalization due to the different model struture. You can check out https://github.com/budzianowski/multiwoz for their data preprocessing.
We will later update results using MultiWOZ2.1 to see if there is any improvement.
